name: build docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker login -u ${{ secrets.DOCKERHUB_NAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -f ./Dockerfile -t ${{ secrets.DOCKERHUB_NAME }}/nsfw-api:latest .
          docker push ${{ secrets.DOCKERHUB_NAME }}/nsfw-api:latest
          docker pull ghcr.io/arnidan/nsfw-api:latest
          docker tag ghcr.io/arnidan/nsfw-api:latest ${{ secrets.DOCKERHUB_NAME }}/ghcr.io_arnidan_nsfw-api:latest
          docker push ${{ secrets.DOCKERHUB_NAME }}/ghcr.io_arnidan_nsfw-api:latest
